# NOTE: update this with your service name
service: auction9-backend

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    # Currently for localhost mysql with default settings
    # Use AWS configs later
    MYSQL_ENDPOINT: localhost
    MYSQL_PORT: 8889
    MYSQL_DATABASE: auction9
    MYSQL_USER: root
    MYSQL_PASSWORD: root

functions:
  # return 'auction' by id
  getAuction:
    handler: handler.getAuction
    events:
      - http:
          path: auctions/{id}
          method: get